---
- name: Enable Satellite Maintenance and Capsule repositories using subscription-manager
  ansible.builtin.shell: subscription-manager repos --enable={{ item }}
  loop:
    - "satellite-maintenance-6.15-for-rhel-8-x86_64-rpms"
    - "satellite-capsule-6.15-for-rhel-8-x86_64-rpms"
  register: enable_repo_result
  changed_when: "'enabled' not in enable_repo_result.stdout"
  failed_when: "'Error' in enable_repo_result.stderr"
  notify:
    - Send repository enablement failure notification
