---
- name: Check if a reboot is required after the upgrade
  ansible.builtin.shell: needs-restarting -r
  register: reboot_needed
  changed_when: reboot_needed.rc == 1
  failed_when: reboot_needed.rc not in [0, 1]

- name: Reboot the system if required
  ansible.builtin.reboot:
  when: reboot_needed.rc == 1

- name: Wait for the system to come back after reboot
  ansible.builtin.wait_for_connection:
    delay: 60
    timeout: 300
  when: reboot_needed.rc == 1
  notify:
    - Send reboot success notification
