---
# handlers file for satellite-upgrade
- name: Send repository enablement failure notification
  ansible.builtin.debug:
    msg: "Failed to enable required repositories for Satellite upgrade."

- name: Send module enablement failure notification
  ansible.builtin.debug:
    msg: "Failed to enable satellite-maintain module for version 6.15."

- name: Send version check failure notification
  ansible.builtin.debug:
    msg: "Satellite version 6.15 is not available in the list."

- name: Send pre-upgrade check failure notification
  ansible.builtin.debug:
    msg: "Pre-upgrade checks for v6.15 failed."

- name: Send upgrade failure notification
  ansible.builtin.debug:
    msg: "Satellite upgrade to v6.15 failed."

- name: Send upgrade success notification
  ansible.builtin.debug:
    msg: "Satellite upgrade to v6.15 completed successfully."

- name: Send reboot success notification
  ansible.builtin.debug:
    msg: "System rebooted successfully after Satellite upgrade."
