---
- name: Perform Satellite upgrade to v6.15
  ansible.builtin.shell: satellite-maintain upgrade run --target-version 6.15 -y
  register: upgrade_result
  changed_when: "'Upgrade completed successfully' in upgrade_result.stdout"
  failed_when: "'ERROR' in upgrade_result.stdout"
  notify:
    - Send upgrade failure notification
    - Send upgrade success notification
